discogs_to_routenote = {

    # ------------------------------------------------------------------------
    # BLUES
    # ------------------------------------------------------------------------
    "Boogie Woogie": "Blues",
    "Chicago Blues": "Blues",
    "Country Blues": "Blues",
    "Delta Blues": "Blues",
    "Electric Blues": "Blues",
    "Harmonica Blues": "Blues",
    "Jump Blues": "Blues",
    "Louisiana Blues": "Blues",
    "Modern Electric Blues": "Blues",
    "Piano Blues": "Blues",
    "Texas Blues": "Blues",
    # Exception: "Rhythm & Blues" -> R&B/Soul
    "Rhythm & Blues": "R&B/Soul",

    # ------------------------------------------------------------------------
    # BRASS & MILITARY
    # ------------------------------------------------------------------------
    "Brass Band": "World",
    "Marches": "World",
    "Military": "World",

    # ------------------------------------------------------------------------
    # CHILDREN'S
    # ------------------------------------------------------------------------
    "Educational": "Children's Music",
    "Story": "Children's Music",

    # ------------------------------------------------------------------------
    # CLASSICAL
    # ------------------------------------------------------------------------
    "Baroque": "Clasical",
    "Choral": "Clasical",
    "Classical": "Clasical",
    "Contemporary": "Clasical",
    "Impressionist": "Clasical",
    "Medieval": "Clasical",
    "Modern": "Clasical",
    "Neo-Classical": "Clasical",
    "Neo-Romantic": "Clasical",
    "Post-Modern": "Clasical",
    "Renaissance": "Clasical",
    "Romantic": "Clasical",
    # Opera has its own category
    "Opera": "Opera",

    # ------------------------------------------------------------------------
    # ELECTRONIC
    # (Mostly mapped to "Electronic", with some exceptions below)
    # ------------------------------------------------------------------------
    "Abstract": "Electronic",
    "Acid": "Electronic",
    "Acid House": "Electronic",
    "Acid Jazz": "Electronic",     # Could arguably go "Jazz", but we'll keep it "Electronic"
    "Ambient": "Electronic",
    "Bassline": "Electronic",
    "Beatdown": "Electronic",
    "Berlin-School": "Electronic",
    "Big Beat": "Electronic",
    "Bleep": "Electronic",
    "Breakbeat": "Electronic",
    "Breakcore": "Electronic",
    "Breaks": "Electronic",
    "Broken Beat": "Electronic",
    "Chillwave": "Electronic",
    "Chiptune": "Electronic",
    "Dance-pop": "Electronic",
    "Dark Ambient": "Electronic",
    "Darkwave": "Electronic",
    "Deep House": "Electronic",
    "Deep Techno": "Electronic",
    "Disco": "Electronic",        # Note that "Disco" also appears under Funk/Soul; here we keep it as Electronic
    "Disco Polo": "Electronic",
    "Donk": "Electronic",
    "Downtempo": "Electronic",
    "Drone": "Electronic",
    "Drum n Bass": "Electronic",
    "Dub": "Electronic",
    "Dub Techno": "Electronic",
    "Dubstep": "Electronic",
    "Dungeon Synth": "Electronic",
    "EBM": "Electronic",
    "Electro": "Electronic",
    "Electro House": "Electronic",
    "Electroclash": "Electronic",
    "Euro House": "Electronic",
    "Euro-Disco": "Electronic",
    "Eurobeat": "Electronic",
    "Eurodance": "Electronic",
    "Experimental": "Electronic",
    "Freestyle": "Electronic",
    "Future Jazz": "Electronic",
    "Gabber": "Electronic",
    "Garage House": "Electronic",
    "Ghetto": "Electronic",
    "Ghetto House": "Electronic",
    "Glitch": "Electronic",
    "Goa Trance": "Electronic",
    "Grime": "Electronic",
    "Halftime": "Electronic",
    "Hands Up": "Electronic",
    "Happy Hardcore": "Electronic",
    "Hard House": "Electronic",
    "Hard Techno": "Electronic",
    "Hard Trance": "Electronic",
    "Hardcore": "Electronic",
    "Hardstyle": "Electronic",
    "Hi NRG": "Electronic",
    "Hip-House": "Electronic",
    "House": "Electronic",
    "IDM": "Electronic",
    "Illbient": "Electronic",
    "Industrial": "Electronic",
    "Italo House": "Electronic",
    "Italo-Disco": "Electronic",
    "Italodance": "Electronic",
    "Jazzdance": "Electronic",
    "Juke": "Electronic",
    "Jumpstyle": "Electronic",
    "Jungle": "Electronic",
    # If "Latin" appears here, we re-map it to "Latin"
    "Latin": "Latin",
    "Leftfield": "Electronic",
    "Makina": "Electronic",
    "Minimal": "Electronic",
    "Minimal Techno": "Electronic",
    # "Modern Classical" => "Clasical"
    "Modern Classical": "Clasical",
    "Musique Concrète": "Electronic",
    # "Neofolk" => "World"
    "Neofolk": "World",
    # "New Age" => "New Age"
    "New Age": "New Age",
    "New Beat": "Electronic",
    # "New Wave" => "Rock"
    "New Wave": "Rock",
    "Noise": "Electronic",
    "Nu-Disco": "Electronic",
    "Power Electronics": "Electronic",
    "Progressive Breaks": "Electronic",
    "Progressive House": "Electronic",
    "Progressive Trance": "Electronic",
    "Psy-Trance": "Electronic",
    "Rhythmic Noise": "Electronic",
    "Schranz": "Electronic",
    "Sound Collage": "Electronic",
    "Speed Garage": "Electronic",
    "Speedcore": "Electronic",
    "Synth-pop": "Electronic",
    "Synthwave": "Electronic",
    "Tech House": "Electronic",
    "Tech Trance": "Electronic",
    "Techno": "Electronic",
    "Trance": "Electronic",
    "Tribal": "Electronic",
    "Tribal House": "Electronic",
    "Trip Hop": "Electronic",
    "Tropical House": "Electronic",
    "UK Garage": "Electronic",
    "Vaporwave": "Electronic",

    # ------------------------------------------------------------------------
    # FOLK, WORLD, & COUNTRY
    # ------------------------------------------------------------------------
    "African": "World",
    "Bluegrass": "Country",
    "Cajun": "Country",
    "Canzone Napoletana": "World",
    "Catalan Music": "World",
    "Celtic": "World",
    "Country": "Country",
    "Fado": "World",
    "Flamenco": "World",
    "Folk": "World",
    "Highlife": "World",
    "Hillbilly": "Country",
    "Hindustani": "Indian",
    "Honky Tonk": "Country",
    "Indian Classical": "Indian",
    "Laïkó": "World",
    "Nordic": "World",
    "Pacific": "World",
    "Polka": "World",
    "Raï": "World",
    "Romani": "World",
    "Soukous": "World",
    "Séga": "World",
    "Volksmusik": "World",
    "Zouk": "World",
    "Éntekhno": "World",

    # ------------------------------------------------------------------------
    # FUNK / SOUL
    # ------------------------------------------------------------------------
    # Everything to "R&B/Soul" except "Gospel" -> "Christian & Gospel", 
    # "Afrobeat" -> "World", and "Disco" -> "Dance"
    "Afrobeat": "World",
    "Boogie": "R&B/Soul",
    "Contemporary R&B": "R&B/Soul",
    "Disco": "Dance",
    "Free Funk": "R&B/Soul",
    "Funk": "R&B/Soul",
    "Gospel": "Christian & Gospel",
    "Neo Soul": "R&B/Soul",
    "New Jack Swing": "R&B/Soul",
    "P.Funk": "R&B/Soul",
    "Psychedelic": "R&B/Soul",  # could also be Rock, but we'll keep it here
    "Soul": "R&B/Soul",
    "Swingbeat": "R&B/Soul",
    "UK Street Soul": "R&B/Soul",

    # ------------------------------------------------------------------------
    # HIP HOP
    # ------------------------------------------------------------------------
    # Map everything to "Hip Hop/Rap"
    "Bass Music": "Hip Hop/Rap",
    "Boom Bap": "Hip Hop/Rap",
    "Bounce": "Hip Hop/Rap",
    "Britcore": "Hip Hop/Rap",
    "Cloud Rap": "Hip Hop/Rap",
    "Conscious": "Hip Hop/Rap",
    "Crunk": "Hip Hop/Rap",
    "Cut-up/DJ": "Hip Hop/Rap",
    "DJ Battle Tool": "Hip Hop/Rap",
    "Electro (Hip Hop)": "Hip Hop/Rap",  # sometimes shown as 'Electro' in hip hop context
    "G-Funk": "Hip Hop/Rap",
    "Gangsta": "Hip Hop/Rap",
    "Grime": "Hip Hop/Rap",  # also appears in Electronic, but if it's under Hip Hop, keep it here
    "Hardcore Hip-Hop": "Hip Hop/Rap",
    "Horrorcore": "Hip Hop/Rap",
    "Instrumental (Hip Hop)": "Hip Hop/Rap",
    "Jazzy Hip-Hop": "Hip Hop/Rap",
    "Miami Bass": "Hip Hop/Rap",
    "Pop Rap": "Hip Hop/Rap",
    "Ragga HipHop": "Hip Hop/Rap",
    "RnB/Swing": "Hip Hop/Rap",
    "Screw": "Hip Hop/Rap",
    "Thug Rap": "Hip Hop/Rap",
    "Trap": "Hip Hop/Rap",
    "Trip Hop": "Hip Hop/Rap",  # also seen in Electronic, but if under Hip Hop keep it consistent
    "Turntablism": "Hip Hop/Rap",

    # ------------------------------------------------------------------------
    # JAZZ
    # ------------------------------------------------------------------------
    # Mostly "Jazz", with some special exceptions
    "Afro-Cuban Jazz": "Jazz",
    # "Afrobeat" here would be "World" if it appears
    "Avant-garde Jazz": "Jazz",
    "Big Band": "Jazz",
    "Bop": "Jazz",
    # "Bossa Nova" -> "Brazilian"
    "Bossa Nova": "Brazilian",
    "Contemporary Jazz": "Jazz",
    "Cool Jazz": "Jazz",
    "Dixieland": "Jazz",
    # "Easy Listening" -> "Easy Listening"
    "Easy Listening": "Easy Listening",
    "Free Improvisation": "Jazz",
    "Free Jazz": "Jazz",
    "Fusion": "Jazz",
    "Gypsy Jazz": "Jazz",
    "Hard Bop": "Jazz",
    "Jazz-Funk": "Jazz",
    "Jazz-Rock": "Jazz",
    # "Latin Jazz" -> "Latin"
    "Latin Jazz": "Latin",
    "Modal": "Jazz",
    "Post Bop": "Jazz",
    "Ragtime": "Jazz",
    "Smooth Jazz": "Jazz",
    "Soul-Jazz": "Jazz",
    "Space-Age": "Jazz",
    "Swing": "Jazz",

    # ------------------------------------------------------------------------
    # LATIN
    # ------------------------------------------------------------------------
    # Most map to "Latin", except certain Brazilian subgenres -> "Brazilian"
    "Afro-Cuban": "Latin",
    "Baião": "Brazilian",
    "Batucada": "Brazilian",
    "Beguine": "Latin",
    "Bolero": "Latin",
    "Boogaloo": "Latin",
    # "Bossanova" spelled here as "Bossa Nova" above => "Brazilian"
    "Cha-Cha": "Latin",
    "Charanga": "Latin",
    "Compas": "Latin",
    "Cubano": "Latin",
    "Cumbia": "Latin",
    "Descarga": "Latin",
    "Forró": "Brazilian",
    "Guaguancó": "Latin",
    "Guajira": "Latin",
    "Guaracha": "Latin",
    "MPB": "Brazilian",
    "Mambo": "Latin",
    "Mariachi": "Latin",
    "Merengue": "Latin",
    "Norteño": "Latin",
    "Nueva Cancion": "Latin",
    "Pachanga": "Latin",
    "Porro": "Latin",
    "Ranchera": "Latin",
    "Reggaeton": "Latin",
    "Rumba": "Latin",
    "Salsa": "Latin",
    "Samba": "Brazilian",
    "Son": "Latin",
    "Son Montuno": "Latin",
    "Tango": "Latin",
    "Tejano": "Latin",
    "Vallenato": "Latin",

    # ------------------------------------------------------------------------
    # NON-MUSIC
    # ------------------------------------------------------------------------
    # Everything -> "Spoken Word" except "Comedy" -> "Comedy"
    "Audiobook": "Spoken Word",
    "Comedy": "Comedy",
    "Dialogue": "Spoken Word",
    "Education": "Spoken Word",
    "Field Recording": "Spoken Word",
    "Interview": "Spoken Word",
    "Monolog": "Spoken Word",
    "Poetry": "Spoken Word",
    "Political": "Spoken Word",
    "Promotional": "Spoken Word",
    "Radioplay": "Spoken Word",
    "Religious": "Spoken Word",
    "Spoken Word": "Spoken Word",  # Redundant, but included for completeness

    # ------------------------------------------------------------------------
    # POP
    # ------------------------------------------------------------------------
    # Everything -> "Pop" except a few that have direct matches in RouteNote
    "Ballad": "Pop",
    "Bollywood": "Indian",
    "Bubblegum": "Pop",
    "Chanson": "Pop",
    "City Pop": "Pop",
    "Europop": "Pop",
    "Indie Pop": "Pop",
    "J-pop": "J-Pop",
    "K-pop": "K-Pop",
    "Kayōkyoku": "Kayokyoku",
    "Light Music": "Pop",
    "Music Hall": "Pop",
    "Novelty": "Pop",
    "Parody": "Pop",
    "Schlager": "Pop",
    "Vocal": "Vocal",

    # ------------------------------------------------------------------------
    # REGGAE
    # ------------------------------------------------------------------------
    "Calypso": "Reggae",
    "Dancehall": "Reggae",
    "Dub (Reggae)": "Reggae",
    "Lovers Rock": "Reggae",
    "Ragga": "Reggae",
    "Reggae": "Reggae",
    "Reggae-Pop": "Reggae",
    "Rocksteady": "Reggae",
    "Roots Reggae": "Reggae",
    "Ska": "Reggae",
    "Soca": "Reggae",

    # ------------------------------------------------------------------------
    # ROCK
    # ------------------------------------------------------------------------
    # For simplicity, *everything* goes to "Rock".  (You could refine further.)
    "AOR": "Rock",
    "Acid Rock": "Rock",
    "Acoustic": "Rock",
    "Alternative Rock": "Rock",  # could go "Alternative"
    "Arena Rock": "Rock",
    "Art Rock": "Rock",
    "Atmospheric Black Metal": "Rock",
    "Avantgarde": "Rock",
    "Beat": "Rock",
    "Black Metal": "Rock",
    "Blues Rock": "Rock",
    "Brit Pop": "Rock",
    "Classic Rock": "Rock",
    "Coldwave": "Rock",
    "Country Rock": "Rock",
    "Crust": "Rock",
    "Death Metal": "Rock",
    "Deathcore": "Rock",
    "Deathrock": "Rock",
    "Depressive Black Metal": "Rock",
    "Doo Wop": "Rock",
    "Doom Metal": "Rock",
    "Dream Pop": "Rock",
    "Emo": "Rock",
    "Ethereal": "Rock",
    "Experimental": "Rock",
    "Folk Metal": "Rock",
    "Folk Rock": "Rock",
    "Funeral Doom Metal": "Rock",
    "Funk Metal": "Rock",
    "Garage Rock": "Rock",
    "Glam": "Rock",
    "Goregrind": "Rock",
    "Goth Rock": "Rock",
    "Gothic Metal": "Rock",
    "Grindcore": "Rock",
    "Grunge": "Rock",
    "Hard Rock": "Rock",
    "Hardcore": "Rock",
    "Heavy Metal": "Rock",
    "Indie Rock": "Rock",
    "Industrial (Rock)": "Rock",
    "Krautrock": "Rock",
    "Lo-Fi": "Rock",
    "Lounge": "Rock",
    "Math Rock": "Rock",
    "Melodic Death Metal": "Rock",
    "Melodic Hardcore": "Rock",
    "Metalcore": "Rock",
    "Mod": "Rock",
    "Neofolk (Rock)": "Rock",
    "New Wave (Rock)": "Rock",
    "No Wave": "Rock",
    "Noise (Rock)": "Rock",
    "Noisecore": "Rock",
    "Nu Metal": "Rock",
    "Oi": "Rock",
    "Parody (Rock)": "Rock",
    "Pop Punk": "Rock",
    "Pop Rock": "Rock",
    "Pornogrind": "Rock",
    "Post Rock": "Rock",
    "Post-Hardcore": "Rock",
    "Post-Metal": "Rock",
    "Post-Punk": "Rock",
    "Power Metal": "Rock",
    "Power Pop": "Rock",
    "Power Violence": "Rock",
    "Prog Rock": "Rock",
    "Progressive Metal": "Rock",
    "Psychedelic Rock": "Rock",
    "Psychobilly": "Rock",
    "Pub Rock": "Rock",
    "Punk": "Rock",
    "Rock & Roll": "Rock",
    "Rockabilly": "Rock",
    "Shoegaze": "Rock",
    "Ska (Rock)": "Rock",
    "Sludge Metal": "Rock",
    "Soft Rock": "Rock",
    "Southern Rock": "Rock",
    "Space Rock": "Rock",
    "Speed Metal": "Rock",
    "Stoner Rock": "Rock",
    "Surf": "Rock",
    "Symphonic Rock": "Rock",
    "Technical Death Metal": "Rock",
    "Thrash": "Rock",
    "Twist": "Rock",
    "Viking Metal": "Rock",
    "Yé-Yé": "Rock",

    # ------------------------------------------------------------------------
    # STAGE & SCREEN
    # ------------------------------------------------------------------------
    # Everything -> "Soundtrack"
    "Musical": "Soundtrack",
    "Score": "Soundtrack",
    "Soundtrack": "Soundtrack",  # Redundant but included
    "Theme": "Soundtrack",
}
