jamendo_to_moods = {
    "action":      "Energetic",
    "adventure":   "Fierce",
    "advertising": "Energetic",
    "background":  "Chill",
    "ballad":      "Romantic",   # Many ballads are love-related
    "calm":        "Chill",
    "children":    "Happy",      # Closest approximation
    "christmas":   "Happy",      # Often joyful/festive
    "commercial":  "Energetic",
    "cool":        "Chill",
    "corporate":   "Chill",      # Could also be "Energetic" if upbeat
    "dark":        "Fierce",
    "deep":        "Meditative",
    "documentary": "Chill",      # Tends to be laid-back, neutral
    "drama":       "Sad",
    "dramatic":    "Fierce",
    "dream":       "Chill",
    "emotional":   "Sad",
    "energetic":   "Energetic",
    "epic":        "Energetic",
    "fast":        "Energetic",
    "fun":         "Happy",
    "funny":       "Happy",
    "game":        "Energetic",
    "groovy":      "Happy",
    "happy":       "Happy",
    "heavy":       "Fierce",
    "holiday":     "Happy",      # Often cheerful/festive
    "hopeful":     "Happy",
    "inspiring":   "Happy",      # Could also be "Energetic"—subjective
    "love":        "Romantic",
    "meditative":  "Meditative",
    "melancholic": "Sad",
    "melodic":     "Chill",
    "motivational":"Energetic",
    "nature":      "Chill",
    "party":       "Energetic",
    "positive":    "Happy",
    "powerful":    "Fierce",
    "relaxing":    "Chill",
    "romantic":    "Romantic",
    "sad":         "Sad",
    "sexy":        "Sexy",
    "slow":        "Chill",
    "soft":        "Chill",
    "soundscape":  "Meditative",
    "space":       "Meditative",
    "sport":       "Energetic",
    "summer":      "Happy",
    "trailer":     "Energetic",
    "upbeat":      "Energetic",
    "uplifting":   "Happy",
}