instruments = {
    "Accordion", 
    "Acoustic Guitar", 
    "Banjo", 
    "Bass Guitar", 
    "Buzuq", 
    "Cello", 
    "Clarinet", 
    "Djembe", 
    "Drum Kit", 
    "Electric Guitar", 
    "Erhu", 
    "Flute", 
    "Harmonica", 
    "Harp", 
    "Kora", 
    "Mandolin", 
    "Mbira", 
    "Oboe", 
    "Organ", 
    "Oud", 
    "Pedal Steel Guitar", 
    "Piano", 
    "Samples", 
    "Sanxian", 
    "Sarod", 
    "Saxophone", 
    "Sitar", 
    "Steel Drum", 
    "Synthesizer", 
    "Tabla", 
    "Trombone", 
    "Trumpet", 
    "Ukulele", 
    "Violin", 
    "Xylophone"
}