routenote_genres = {
    "Alternative",
    "Anime",
    "Blues",
    "Brazilian",
    "Children's Music",
    "Christian & Gospel",
    "Clasical",
    "Comedy",
    "Country",
    "Dance",
    "Easy Listening",
    "Electronic",
    "Enka",
    "Fitness & Workout",
    "French Pop",
    "German Folk",
    "German Pop",
    "Hip Hop/Rap",
    "Holiday",
    "Indian",
    "Instrumental",
    "J-Pop",
    "Jazz",
    "K-Pop",
    "Karaoke",
    "Kayokyoku",
    "Korean",
    "Latin",
    "New Age",
    "Opera",
    "Pop",
    "R&B/Soul",
    "Reggae",
    "Rock",
    "Singler/Songwriter",
    "Soundtrack",
    "Spoken Word",
    "Vocal",
    "World"
}