spotify_genres = {
    "Folclor Andino", 
    "Basque Folk (Folk Vasco)", 
    "Folk Québécois", 
    "Ambient Noise", 
    "Pop Country", 
    "Música Popular Brasileira", 
    "Latin House", 
    "Electronic", 
    "Vocal Downtempo", 
    "Kizomba", 
    "UK Garage", 
    "Romantic", 
    "N'dombolo", 
    "Medieval", 
    "J-Alternative", 
    "Qawwali", 
    "Southern Rock", 
    "Breakbeat", 
    "Electronica", 
    "Singer-Songwriter", 
    "Jazz", 
    "Baroque", 
    "Banda", 
    "Bassline", 
    "Indie Pop", 
    "Appalachian", 
    "Mariachi", 
    "Afro House", 
    "Bollywood", 
    "Industrial", 
    "Enka", 
    "Personal Attention (ASMR)", 
    "Poetry", 
    "Tech House", 
    "Bhangra", 
    "Meme Rap", 
    "Soul Singer-Songwriter", 
    "French Indie Pop", 
    "Symphony Orchestra", 
    "Flamenco Jazz", 
    "Pop Urbaine", 
    "J-Rock", 
    "Dub", 
    "Algerian Hip-Hop", 
    "Soft Pop", 
    "Chill Pop", 
    "Shaaby", 
    "Nonfiction", 
    "Bongo Flava", 
    "Album Rock", 
    "Hindustani Classical", 
    "Gospel", 
    "Southern Gospel", 
    "Rock Québécois", 
    "Gengetone", 
    "Faith", 
    "Blues Rock", 
    "Schweizer Mundart", 
    "Dubstep", 
    "Jazz Funk", 
    "Chamamé", 
    "Arab Indie", 
    "Pop Québécois", 
    "Catalan Folk (Folk Catalán)", 
    "Kwaito", 
    "Pop Leve", 
    "Cajun", 
    "Retro Soul", 
    "Gospel Blues", 
    "Deutschpop", 
    "Blues Roots", 
    "Khaleeji", 
    "J-Dance/Electronic", 
    "Choral", 
    "Surf Rock", 
    "Positive Country", 
    "Forró", 
    "Indian Fusion", 
    "Pentecostal", 
    "Rap Québécois", 
    "Alternative", 
    "Tunisian Hip-Hop", 
    "IDM", 
    "Folk Punk", 
    "Contemporary Pop", 
    "Bikutsi", 
    "Sharqi", 
    "Tapping (ASMR)", 
    "Jamgrass", 
    "Electropop", 
    "Contemporary Jazz", 
    "Comedy", 
    "Ambient Drone", 
    "Chicago Blues", 
    "Arab Trap", 
    "Folk", 
    "Arabesk", 
    "Indie Singer-Songwriter", 
    "Black Metal", 
    "Native American Roots", 
    "Nu-Metal", 
    "Volksmusik", 
    "Traditional Folk", 
    "Beats", 
    "Pisadinha", 
    "Retro Rock", 
    "Chicha", 
    "Irish Traditional", 
    "Modern Rock", 
    "Austro Pop", 
    "Folklore Québécois", 
    "Post-Rock", 
    "Garage Rock", 
    "Shamstep", 
    "Lo-Fi Hip-Hop", 
    "Roleplay (ASMR)", 
    "K-Pop", 
    "Mechanical (ASMR)", 
    "Sierreño", 
    "Afrikaans", 
    "Trip Hop", 
    "Alternative Metal", 
    "Big Room", 
    "Murga", 
    "Rai", 
    "Folclor Llanero", 
    "Djent", 
    "Dembow", 
    "Country Québécois", 
    "Disco", 
    "Merengue", 
    "Vallenato", 
    "Future Bass", 
    "Dance House", 
    "Sones", 
    "Conscious Hip-Hop", 
    "Norteño", 
    "Mediterranean", 
    "Classic Rock", 
    "Rominimal", 
    "Crunk", 
    "Acoustic Folk", 
    "Death Metal", 
    "Whispering (ASMR)", 
    "Rumba (Congolese)", 
    "Americana", 
    "Lo-Fi Pop", 
    "Bluegrass", 
    "Country Rock", 
    "Turkish trap pop", 
    "Stoner Metal", 
    "Khaleeji Saudi", 
    "Tropical House", 
    "J-Pop", 
    "Britpop", "Blues Singer-Songwriter", 
    "Música Cristã", 
    "Motswako", 
    "Songs for Life", 
    "Laiko", 
    "Lo-Fi Rock", 
    "Chillstep", 
    "Celtic Punk", 
    "Emo", 
    "Khaleeji Kuwaiti", 
    "Tango", 
    "Roots Reggae", 
    "Spiritual", 
    "Happy Hardcore", 
    "Carnatic Classical", 
    "Reggae", 
    "Música Nativista", 
    "Liedermacher", 
    "Chutney", 
    "Outlaw Country", 
    "Electro", 
    "Funk Carioca", 
    "Jazz Rap", 
    "Khaleeji Iraqi", 
    "Drill", 
    "Bregafunk", 
    "Bass House", 
    "Afro Soul", 
    "Hyperpop", 
    "Hard Rock", 
    "Axé", 
    "Khaleeji Hip-Hop", 
    "EDM", 
    "Mulatós", 
    "Skate Punk", 
    "Disco House", 
    "Contemporary", 
    "Cumbia", 
    "Funk Rock", 
    "Cloud Rap", 
    "Pagode", 
    "Chillhop", 
    "Afropop", 
    "Soca", 
    "Soul Pop", 
    "Electro house", 
    "Indie Bluegrass", 
    "Baltimore Club", 
    "Sheilat", 
    "Rap Napoletano", 
    "Egyptian Pop", 
    "Acoustic Soul", 
    "Latin", 
    "Khaleeji Emirati", 
    "Carimbó", 
    "Hip-Hop", 
    "Lo-Fi House", 
    "Bolero (Latin)", 
    "Spoken Word", 
    "Psychedelic Electronic", 
    "Heavy Metal", 
    "Jazz Beats", 
    "Mandopop", 
    "Pagode Baiano", 
    "minimalism", 
    "Turkish pop", 
    "Bolero (Vietnamese)", 
    "Zouk", 
    "Adult Contemporary", 
    "R&B", 
    "Electronic Gospel", 
    "Soul Funk", 
    "Louisiana Blues", 
    "Thai Pop", 
    "Variété Urbaine", 
    "Electro R&B", 
    "Schlager", 
    "J-Tracks", 
    "Mizrahit", 
    "Soul House", 
    "CCM", 
    "Dabke",
    "Russian Chanson",
    "Children's Music",
    "Dancehall",
    "Shimmer Pop",
    "Southern Rap",
    "Genge",
    "Swing",
    "Alt-Pop",
    "Dance Pop",
    "Afro-Cuban Jazz",
    "Pop Française",
    "Techno",
    "Flamenco Pop",
    "Trap Latino",
    "Deathcore",
    "Drum & Bass",
    "Stoner Rock",
    "Arabic Jazz",
    "Bossa Nova",
    "Nature Noise",
    "New Classic",
    "Experimental Beats",
    "Roots Rock",
    "Chanson Alternative",
    "Folklore Argentino",
    "Arabic Hip-Hop",
    "Club Music", 
    "Downtempo", 
    "Grime",
    "Crossover",
    "Folk Blues",
    "Folk Rock",
    "Binaural Beats",
    "Symphony",
    "Physical Touch (ASMR)", 
    "Electro Shaabi",
    "Indie Dance",
    "Dansband",
    "Metalcore",
    "Ambient",
    "Renaissance",
    "Post-Punk",
    "Huayno",
    "Neomelodico Napoletano",
    "Crinkling (ASMR)",
    "Classical Piano",
    "Juke",
    "Traditional Country",
    "Acoustic Country",
    "Moombahton",
    "Free Jazz",
    "Rock",
    "Indie Québécois",
    "Trapanele",
    "Candombe",
    "Synthwave/Retrowave",
    "Funk",
    "Melodic House",
    "ASMR",
    "Experimental Jazz",
    "Grunge",
    "Freestyle",
    "Lo-Fi Beats",
    "Egyptian Hip-hop",
    "Chanson Française",
    "Massage (ASMR)",
    "Krautrock",
    "Deep House",
    "Trap",
    "Maloya",
    "Indie Electronic",
    "Texas Country",
    "Smooth Jazz",
    "Acoustic Pop",
    "Country Singer Songwriter",
    "Salsa Choke",
    "Christian Rock",
    "Pow Wow",
    "Roots",
    "Neoclassical", 
    "Texas Blues",
    "Psy-Trance",
    "Fado",
    "Progressive Rock",
    "Samba", 
    "Contemporary Christian",
    "Tecnobrega",
    "Champeta",
    "Kuduro",
    "Electronic Flamenco (Flamenco electrónico)",
    "Arrocha",
    "Vaporwave",
    "Sertanejo",
    "Trap Beats",
    "String Orchestra",
    "Jersey Club",
    "Flamenco Chill",
    "Variété Française",
    "Bedroom Pop",
    "Symphonic Metal",
    "Cuarteto", 
    "Pop Rock",
    "Alternative Hip-Hop",
    "Emo Rap",
    "Glam Rock",
    "Maghreb Indie",
    "Hard Bop",
    "Progressive House",
    "Alternative R&B",
    "Pop Rap",
    "Bass",
    "Hill Country Blues", 
    "Pop Singer-Songwriter",
    "Pop R&B",
    "J-R&B/Soul",
    "House",
    "Rock Singer-Songwriter",
    "Indie Folk",
    "Folclor Pacifico",
    "Ambient Folk",
    "Soul", 
    "Ballroom/Vogue",
    "Deutschrap",
    "Chill Beats",
    "Pop Punk",
    "None of these",
    "Eating (ASMR)",
    "Hardcore Techno",
    "Slap House",
    "Rock & Roll",
    "Ska",
    "Jazz Blues",
    "Pop",
    "Highlife", 
    "Kindermusik", 
    "Alt-Country",
    "Jungle",
    "Dance",
    "Folk Pop",
    "Filmi",
    "Coupé Décalé",
    "Dreampop", 
    "Progressive Metal",
    "Slim (ASMR)",
    "Experimental Rock",
    "Thai Country",
    "Footwork",
    "Thrash Metal",
    "Taiwanese/Hokkien",
    "Hakka",
    "Flamenco",
    "Miami Jook",
    "Reggaeton",
    "Zydeco",
    "Audio Plays",
    "Trance",
    "Disco Polo",
    "Rockabilly",
    "Mor Lum",
    "Salsa",
    "Future Funk",
    "M'balax",
    "J-Hip Hop",
    "Manele",
    "Mahraganat",
    "Acid Jazz",
    "Boogie Woogie",
    "Brega",
    "Moroccan Hip-Hop",
    "Entekhno",
    "Brazilian Funk",
    "Cool Jazz",
    "Indie Punk",
    "Jazz Fusion",
    "Liturgical", 
    "Indie Rock",
    "Traditional Gospel",
    "OPM",
    "Folk Metal",
    "lowercase",
    "Honky Tonk",
    "Acoustic Singer-Songwriter",
    "Chillwave", 
    "Ghazal",
    "Jam Band",
    "Classical",
    "Hardcore Punk",
    "Arab Pop",
    "Devotional", 
    "Bubblegum Pop",
    "Digital Maskandi",
    "Rap",
    "East Coast Hip-Hop",
    "Gqom",
    "Chanson Québécois",
    "Afrobeat",
    "New Orleans Bounce",
    "UK Funky",
    "Anime",
    "Fiction",
    "Minimal Techno",
    "Worship",
    "Shoegaze",
    "Funk Beats",
    "Goth",
    "Delta Blues",
    "Psychobilly",
    "Indian Indie",
    "Big Band",
    "Acoustic Rock",
    "Folk Singer-Songwriter",
    "Alternative Rock",
    "Ambient House",
    "Country Rap",
    "Amapiano",
    "Maskandi",
    "Horror Punk",
    "Lo-Fi",
    "Pop Funk",
    "R&B Québécois",
    "Nu Disco",
    "Post Bop",
    "Bachata",
    "Hardstyle",
    "Outros (Brasil)",
    "West Coast Hip-Hop",
    "Country", 
    "Bebop",
    "Cantopop",
    "Hymns",
    "Corrido",
    "Urban Flamenco (Flamenco urbano)",
    "Punk",
    "Philly Club",
    "G House",
    "Neo Soul",
    "Soft Rock",
    "New Jack Swing",
    "Lounge",
    "Tribal House", 
    "Psychedelic", 
    "Future House",
    "Tejano",
    "Jump Blues", 
    "Castilian Folk (Folk Castellano)", 
    "Soukouss",
    "Maghreb Pop"
}